import React, { useContext, useState } from 'react';
import { ThemeContext, useAuth } from '../App';
import { Cpu, RefreshCw, CheckCircle } from 'lucide-react';
import '../styles/AITestCaseGenerator.css';

const AITestCaseGenerator = ({ problemId }) => {
    const { theme } = useContext(ThemeContext);
    const { user } = useAuth();
    const [testCases, setTestCases] = useState([]);
    const [generating, setGenerating] = useState(false);
    const [count, setCount] = useState(5);
    const token = localStorage.getItem('authToken');

    const generateTestCases = async () => {
        setGenerating(true);
        try {
            const response = await fetch('/api/ai/generate-test-cases', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${token}`,
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    problem_id: problemId,
                    count: count
                })
            });

            if (response.ok) {
                const data = await response.json();
                setTestCases(data.testCases || []);
            }
        } catch (error) {
            console.error('Error generating test cases:', error);
        } finally {
            setGenerating(false);
        }
    };

    return (
        <div className={`ai-test-case-gen ${theme}`}>
            <div className="gen-header">
                <h3>
                    <Cpu size={20} />
                    AI Test Case Generator
                </h3>
            </div>

            <div className="gen-controls">
                <div className="control-group">
                    <label>Number of Test Cases:</label>
                    <input
                        type="number"
                        min="1"
                        max="20"
                        value={count}
                        onChange={(e) => setCount(parseInt(e.target.value))}
                    />
                </div>
                <button
                    className="gen-btn"
                    onClick={generateTestCases}
                    disabled={generating}
                >
                    <RefreshCw size={16} />
                    {generating ? 'Generating...' : 'Generate Test Cases'}
                </button>
            </div>

            {testCases.length > 0 && (
                <div className="test-cases-list">
                    {testCases.map((tc, idx) => (
                        <div key={idx} className="test-case">
                            <div className="test-header">
                                <span className="test-num">Test Case {idx + 1}</span>
                                <span className="test-status">
                                    <CheckCircle size={14} />
                                    Generated by AI
                                </span>
                            </div>
                            <div className="test-input">
                                <strong>Input:</strong>
                                <pre>{tc.input}</pre>
                            </div>
                            <div className="test-output">
                                <strong>Expected Output:</strong>
                                <pre>{tc.expectedOutput}</pre>
                            </div>
                            {tc.explanation && (
                                <div className="test-explanation">
                                    <strong>Explanation:</strong>
                                    <p>{tc.explanation}</p>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default AITestCaseGenerator;
